### ISSUE TITLE
When i turn the plugin to minigames mode i get error in my console

### ISSUE THREAD

**Issue by TLeung094** [Shynixn/BlockBall#111]
When i turn the plugin to minigames mode i get error in my console.
I using 1.12.2 paperspigot

> [22:08:58 ERROR]: Could not pass event PlayerInteractEvent to BlockBall v5.2.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1402]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1402]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1402]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: com.github.shynixn.blockball.lib.kotlin.KotlinNullPointerException
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.prepareLobbyStatsForPlayer(Minigame.kt:369) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.join(Minigame.kt:133) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.join(Minigame.kt:54) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.listener.GameListener.onClickOnPlacedSign(GameListener.kt:150) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-latest.jar:git-Paper-1402]
        ... 18 more

**Comment by Shynixn** [comment]
I think you did not set the lobby spawnpoint yet? :)

https://shynixn.github.io/BlockBall/build/html/gamemodes/minigame.html#configuring-ingame
