### ISSUE TITLE
Game inventory joining issue. 36 Slots issue.

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#114]
[BlockBall] Task #30 for BlockBall v5.3.0 generated an exception
java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[FootBall.jar:git-PaperSpigot-"4c7641d"]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.joinTeam(Minigame.kt:359) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.startGame(Minigame.kt:317) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.onTwentyTicks(Minigame.kt:246) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.LowLevelGame.run(LowLevelGame.kt:124) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.SoccerGame.run(SoccerGame.kt:67) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.controller.GameRepository.run(GameRepository.kt:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[FootBall.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Shynixn** [comment]
java.lang.IllegalArgumentException: Invalid inventory size; expected 36 or less
        at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.setContents(CraftInventory.java:64) ~[FootBall.jar:git-PaperSpigot-"4c7641d"]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.joinTeam(Minigame.kt:359) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.startGame(Minigame.kt:317) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.Minigame.onTwentyTicks(Minigame.kt:246) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.LowLevelGame.run(LowLevelGame.kt:124) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.entity.game.SoccerGame.run(SoccerGame.kt:67) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.controller.GameRepository.run(GameRepository.kt:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[FootBall.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [FootBall.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [FootBall.jar:git-PaperSpigot-"4c7641d"]
