### ISSUE TITLE
Can't set money reward

### ISSUE THREAD

**Issue by BZEagle** [Shynixn/BlockBall#165]
This is the warning:
[BlockBall] Cannot read arena file arena_1.yml.
java.lang.IllegalArgumentException: Cannot instanciet the class class java.lang.Integer. Does it have a default constructor?
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserialize(YamlSerializationServiceImpl.kt:77) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeMap(YamlSerializationServiceImpl.kt:145) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeField(YamlSerializationServiceImpl.kt:248) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeObject(YamlSerializationServiceImpl.kt:191) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserialize(YamlSerializationServiceImpl.kt:80) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeField(YamlSerializationServiceImpl.kt:260) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeObject(YamlSerializationServiceImpl.kt:191) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserialize(YamlSerializationServiceImpl.kt:80) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeField(YamlSerializationServiceImpl.kt:260) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserializeObject(YamlSerializationServiceImpl.kt:191) ~[?:?]
        at com.github.shynixn.blockball.core.logic.business.service.YamlSerializationServiceImpl.deserialize(YamlSerializationServiceImpl.kt:80) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.persistence.repository.ArenaFileRepository.getAll(ArenaFileRepository.kt:56) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.service.PersistenceArenaServiceImpl$refresh$$inlined$async$2.run(ExtensionMethods.kt:399) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[Paper-1.13.2-abba3d1-20190203-1534.jar:git-Paper-"abba3d11"]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[Paper-1.13.2-abba3d1-20190203-1534.jar:git-Paper-"abba3d11"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paper-1.13.2-abba3d1-20190203-1534.jar:git-Paper-"abba3d11"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Shynixn** [comment]
* This looks like a arena file parsing exception. Did you set the money reward via the chat ui ingame? Can you also please share this config file via pastbin with me?

**Comment by Shynixn** [comment]
I have fixed this issue in the latest snapshot. Thanks for reporting.
