### ISSUE TITLE
CommandException: Unhandled exception executing 'bbc'

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#19]
blockball-3.8.1-20170303.142405-2.jar

```
[01:39:08 INFO]: player issued server command: /bbc
[01:39:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bbc' in com.github.shynixn.blockball.business.logic.arena.ArenaCommandExecutor$1(bbc)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[patched_1.11.2.jar:git-Paper-1063]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) ~[patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1384) ~[patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) ~[patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.11.2.jar:git-Paper-1063]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1063]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1063]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.github.shynixn.blockball.lib.SChatMenuManager.handleChatMessage(SChatMenuManager.java:37) ~[?:?]
        at com.github.shynixn.blockball.business.logic.arena.ArenaCommandExecutor$1.onCommandSend(ArenaCommandExecutor.java:37) ~[?:?]
        at com.github.shynixn.blockball.lib.DynamicCommandHelper.execute(DynamicCommandHelper.java:32) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.2.jar:git-Paper-1063]
        ... 14 more
```

```
navigate-chatmenu:
  enabled: true
  command: bbc
  useage: /<command>
  description: Helps navigating through the chamenu.
  permission: blockball.admin
  permission-message: You don't have permission
```

**Comment by Shynixn** [comment]
This build seems to contain various problems. Thanks for the screenshots, fixing it.

**Comment by Shynixn** [comment]
* Fixed in the latest snapshot
