### ISSUE TITLE
Refactor PackageService

### ISSUE THREAD

**Issue by Giancarmine** [Shynixn/BlockBall#336]
- The functionality of the PackageService should be move to the ProxyService.
- Move the function sendPacket from the com.github.shynixn.blockball.api.business.service.PackageService class to com.github.shynixn.blockball.api.business.service.ProxyService. (including all implementaions)
- Remove com.github.shynixn.blockball.api.business.service.PackageService and all implementations of it.
- Replace all calls to the $PackageService.sendPacket function with calls to the $ProxyService.sendPacket function.
- Make sure the project still compiles afterwards and passes all tests.

**Comment by Giancarmine** [comment]
Hi there, I`m trying setup the project (following the tips in the readme file), but i have the following error

```bash
Picked up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true
ott 09, 2020 6:58:15 PM org.bukkit.Bukkit setServer
INFORMAZIONI: This server is running TestServer version Version_null (Implementing API version BukkitVersion_null)
ott 09, 2020 6:58:43 PM org.bukkit.Bukkit setServer
INFORMAZIONI: This server is running org.bukkit.support.DummyServer version null (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Could not get version 1.9.4 does it exist? Try another version or use 'latest'
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.spigotmc.builder.Builder.get(Builder.java:679)
        at org.spigotmc.builder.Builder.main(Builder.java:318)
        at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:34)

> Task :downloadDependencies FAILED

FAILURE: Build failed with an exception.
```

I`m in a linux mint environment during the downloadDependencies step

**Comment by Shynixn** [comment]
Hi @Giancarmine !

Strange, the travis ci build server is also running on linux and is able to download and install the dependencies.
Anyway for linux it is quite simple to manually install it:

1.  Download https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar 
2.  Take a look at the [commands on this page](https://github.com/Shynixn/BlockBall/blob/bb7a65745440ef5578f6495a7380354cb64870c4/build.gradle#L262) and simply execute the commands one after another. You do not have to be in a specific folder. 

You don't need to execute ``mvn install:install-file -Dfile=Vault.jar`` as it seems like that you have already installed it.
