### ISSUE TITLE
this error i think it shows when i starts the server

### ISSUE THREAD

**Issue by HEMO313** [Shynixn/BlockBall#439]
[20:29:06 WARN]: java.lang.RuntimeException: Impl not found!
[20:29:06 WARN]:        at com.github.shynixn.blockball.bukkit.logic.business.service.ProtocolServiceImpl$channelField$2.invoke(ProtocolServiceImpl.kt:60)
[20:29:06 WARN]:        at com.github.shynixn.blockball.bukkit.logic.business.service.ProtocolServiceImpl$channelField$2.invoke(ProtocolServiceImpl.kt:49)
[20:29:06 WARN]:        at com.github.shynixn.blockball.lib.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[20:29:06 WARN]:        at com.github.shynixn.blockball.bukkit.logic.business.service.ProtocolServiceImpl.getChannelField(ProtocolServiceImpl.kt:49)
[20:29:06 WARN]:        at com.github.shynixn.blockball.bukkit.logic.business.service.ProtocolServiceImpl.register(ProtocolServiceImpl.kt:94)
[20:29:06 WARN]:        at com.github.shynixn.blockball.bukkit.logic.business.listener.BallListener.onPlayerJoinEvent(BallListener.kt:33)
[20:29:06 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:29:06 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:29:06 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:29:06 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[20:29:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[20:29:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[20:29:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:29:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564)
[20:29:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:313)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:172)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:150)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:60)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:471)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:183)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1016)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:814)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:647)
[20:29:06 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133)
[20:29:06 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Shynixn** [comment]
Probably your server framework is not supported. Only Spigot and Paper is officially supported.

**Comment by HEMO313** [comment]
> Probably your server framework is not supported. Only Spigot and Paper is officially supported.

panadaspigot its a fork from paper

**Comment by Shynixn** [comment]
Yes, but as it is a fork they may contain changes which makes BlockBall incompatible. Sorry, but you are on your own.
