### ISSUE TITLE
Wand destroys block

### ISSUE THREAD

**Issue by e-motiv** [Shynixn/BlockBall#441]
Wordledit 7.2.13 / Bukkit 7.2.13
When left clicking with the wand the block gets destroyed.
Sometimes it works and it does not get destroyed. when that happens , I can left click hundred times and nothing gets destroyed.  It seems to be related with the second selection point or right clicking the block before left clicking... I can't figure it out..

**Comment by e-motiv** [comment]
Actually a lot of commands bug out. Here is the log from a simple expand.

17.03 21:03:16 [Server] INFO Stonee666 issued server command: //expand 1 u
17.03 21:03:16 [Server] ERROR An unexpected error while handling a WorldEdit command
17.03 21:03:16 [Server] INFO java.lang.NoSuchFieldError: networkManager
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.bukkit.adapter.impl.v1_19_R2.PaperweightAdapter.sendFakeNBT(PaperweightAdapter.java:529) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitPlayer.sendFakeBlock(BukkitPlayer.java:302) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.extension.platform.PlayerProxy.sendFakeBlock(PlayerProxy.java:189) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.LocalSession.updateServerCUI(LocalSession.java:837) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.LocalSession.dispatchCUIEvent(LocalSession.java:858) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.regions.selector.CuboidRegionSelector.explainRegionAdjust(CuboidRegionSelector.java:197) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.command.ExpandCommands.expand(ExpandCommands.java:152) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.command.ExpandCommandsRegistration.cmd$_expand(ExpandCommandsRegistration.java:102) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:383) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.13.jar:?]
17.03 21:03:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
17.03 21:03:16 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
17.03 21:03:16 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
17.03 21:03:16 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
17.03 21:03:16 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Shynixn** [comment]
Hello. Why do you think that BlockBall is causing this error? I don't see any hint of blockball in your error stacktrace.

**Comment by e-motiv** [comment]
I'm so sorry!  No idea how I end up on BlockBall. I was browsing the issues on worldedit and I have no clue how I end up here.  Probably wrong tab while I was searching for some words.
Me culpa... You can delete this issue..
