### ISSUE TITLE
PlayerJoinEvent erorr BlockBall v6.34.0 (1.19.3)

### ISSUE THREAD

**Issue by Technofied** [Shynixn/BlockBall#448]
Keep getting this error on join, not quite sure why

[04:07:50 ERROR]: Could not pass event PlayerJoinEvent to BlockBall v6.34.0
java.lang.IllegalArgumentException: Can not set final net.minecraft.network.NetworkManager field net.minecraft.server.network.PlayerConnection.b to net.minecraft.server.dedicated.DedicatedServer
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.service.ProtocolServiceImpl.register(ProtocolServiceImpl.kt:101) ~[BlockBall.jar:?]
        at com.github.shynixn.blockball.bukkit.logic.business.listener.BallListener.onPlayerJoinEvent(BallListener.kt:33) ~[BlockBall.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1016.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-59]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:319) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:585) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Shynixn** [comment]
Should be fixed in the latest version
