### ISSUE TITLE
Error appears when player runs onto field without joining a team

### ISSUE THREAD

**Issue by Technofied** [Shynixn/BlockBall#452]
See below error. Player is then able to fly

[12:47:43 ERROR]: Could not pass event PlayerMoveEvent to BlockBall v6.34.1
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.github.shynixn.blockball.bukkit.logic.business.service.HubGameForcefieldServiceImpl.checkForForcefieldInteractions(HubGameForcefieldServiceImpl.kt:119) ~[BlockBall.jar:?]
        at com.github.shynixn.blockball.bukkit.logic.business.listener.HubgameListener.onPlayerMoveAgainstHubForceField(HubgameListener.kt:48) ~[BlockBall.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1019.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-59]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1594) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1391) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Technofied** [comment]
It appears the fly bug is separate. Essentially if you are boxed in an arena, and haven't chosen a team yet, it'll fling you around until you start flying

**Comment by Shynixn** [comment]
The ``join-selection`` values need to be exactly 3 lines:

https://github.com/Shynixn/BlockBall/blob/210bd6ca181ecf4027e1ab519145194efe734cba/blockball-tools/arena-files/arena/arena_1.yml#L39
