### ISSUE TITLE
BlockBall plugin does not fully load if an arena validation exception occurs. The plugin should still load even if the user has not set all required settings

### ISSUE THREAD

**Issue by thiagogebrimm** [Shynixn/BlockBall#545]
```
[20:01:39 ERROR]: [BlockBall] This is not an error of MCCoroutine! See sub exception for details.
java.io.IOException: Cannot connect create connection to SQLite database /home/container/plugins/BlockBall/BlockBall.sqlite. Check your startup log for errors.
        at BlockBall-7.1.0.jar/com.github.shynixn.blockball.lib.com.github.shynixn.mcutils.database.impl.SqliteConnectionServiceImpl.getConnection(SqliteConnectionServiceImpl.kt:65) ~[BlockBall-7.1.0.jar:?]
        at BlockBall-7.1.0.jar/com.github.shynixn.blockball.lib.com.github.shynixn.mcutils.database.impl.PlayerDataSqlRepositoryImpl$getByPlayerUUID$2.invokeSuspend(PlayerDataSqlRepositoryImpl.kt:121) ~[BlockBall-7.1.0.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[?:?]
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) ~[?:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[?:?]
```

**Comment by Shynixn** [comment]
Check your startup log for any errors. A message smilar to
`` [BlockBall] Connecting to SQLite database C:\temp\plugins\BlockBall\BlockBall.sqlite`` should appear.

**Comment by thiagogebrimm** [comment]
```
[14:01:13] [Server thread/ERROR]: [BlockBall] This is not an error of MCCoroutine! See sub exception for details.
com.github.shynixn.blockball.impl.exception.SoccerGameException: Set the red lobby spawnpoint for arena 1!
	at BlockBall-7.1.0.jar/com.github.shynixn.blockball.impl.service.GameServiceImpl.validateGame(GameServiceImpl.kt:234) ~[BlockBall-7.1.0.jar:?]
	at BlockBall-7.1.0.jar/com.github.shynixn.blockball.impl.service.GameServiceImpl.reload(GameServiceImpl.kt:91) ~[BlockBall-7.1.0.jar:?]
	at BlockBall-7.1.0.jar/com.github.shynixn.blockball.impl.service.GameServiceImpl.reloadAll(GameServiceImpl.kt:67) ~[BlockBall-7.1.0.jar:?]
	at BlockBall-7.1.0.jar/com.github.shynixn.blockball.impl.service.GameServiceImpl$reloadAll$1.invokeSuspend(GameServiceImpl.kt) ~[BlockBall-7.1.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[?:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2287-07979c3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Shynixn** [comment]
I see, set the required spawnspoints. But this actually a bug with the plugin loading in 7.1.0
