### ISSUE TITLE
LowLevel game kotlin map throws modification exception

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/BlockBall#85]
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_161]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_161]
    at com.github.shynixn.blockball.bukkit.logic.business.entity.game.LowLevelGame.updateDoubleJumpCooldown(LowLevelGame.kt:402) ~[?:?]
    at com.github.shynixn.blockball.bukkit.logic.business.entity.game.LowLevelGame.run(LowLevelGame.kt:129) ~[?:?]
    at com.github.shynixn.blockball.bukkit.logic.business.entity.game.SoccerGame.run(SoccerGame.kt:67) ~[?:?]
    at com.github.shynixn.blockball.bukkit.logic.business.controller.GameRepository.run(GameRepository.kt:109) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]

**Comment by Shynixn** [comment]
#93
